### PR TITLE
Add the option to upload bytes  object

### LINKED ISSUE #67: feature request: support for in memory upload/download media
Thanks a lot for this great library!

I would like to use it in a tool that performs automated backups of autodesk bim360 files (but it could be any other storage service) to a google drive folder.

As of now, the only way to use the drive method `files.create()` is to specify the `upload_file` parameter as the file path, but I would like to use a file object (the one downloaded from the other service) without writing it to memory first.

I see that the `fire_request` coroutine in `AiohttpSession.send` does the reading of the file via `aiofiles.open`, and then passes the file object (or `MultipartWriter` object) to `self.request`.

Do you think it could be a good addition to support my use case?

If so, I could try to make a PR for that, but I would like to know your thoughts on this (and tips on how to accomplish this in a clean way).

### PR DESCRIPTION
**Pull request by sanzoghenzo**
this closes #67

Unit tests for the new `MediaUpload` methods are in place.

As a bonus, I also edited the API refresh script and `conftest.py` to handle paths regardless of the working directory.

### CODE REVIEW

**Comment by omarryhan** [comment]
Awesome stuff, thanks!

I'm trying to run the `upload_drive_file.py` example and it's giving me this error:

```
(aiogoogle) omar@DESKTOP-2D7FN3P:~/aiogoogle/examples$ python upload_drive_file.py /mnt/c/Users/Omar/Desktop/sample.pdf sample.pdf
Traceback (most recent call last):
  File "/home/omar/aiogoogle/lib/python3.8/site-packages/aiohttp/multipart.py", line 796, in append
    payload = get_payload(obj, headers=headers)
  File "/home/omar/aiogoogle/lib/python3.8/site-packages/aiohttp/payload.py", line 73, in get_payload
    return PAYLOAD_REGISTRY.get(data, *args, **kwargs)
  File "/home/omar/aiogoogle/lib/python3.8/site-packages/aiohttp/payload.py", line 112, in get
    raise LookupError()
aiohttp.payload.LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "upload_drive_file.py", line 56, in <module>
    asyncio.run(upload_file(full_path, new_name))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "upload_drive_file.py", line 38, in upload_file
    upload_res = await aiogoogle.as_user(req)
  File "/home/omar/aiogoogle/aiogoogle/client.py", line 239, in as_user
    return await self.send(
  File "/home/omar/aiogoogle/aiogoogle/client.py", line 366, in send
    return await self.active_session.send(*args, **kwargs)
  File "/home/omar/aiogoogle/aiogoogle/sessions/aiohttp_session.py", line 172, in send
    results = await schedule_tasks()
  File "/home/omar/aiogoogle/aiogoogle/sessions/aiohttp_session.py", line 164, in schedule_tasks
    return await asyncio.gather(*tasks, return_exceptions=False)
  File "/home/omar/aiogoogle/aiogoogle/sessions/aiohttp_session.py", line 150, in get_content
    response = await get_response(request)
  File "/home/omar/aiogoogle/aiogoogle/sessions/aiohttp_session.py", line 143, in get_response
    response = await fire_request(request)
  File "/home/omar/aiogoogle/aiogoogle/sessions/aiohttp_session.py", line 98, in fire_request
    mpwriter.append(
  File "/home/omar/aiogoogle/lib/python3.8/site-packages/aiohttp/multipart.py", line 798, in append
    raise TypeError("Cannot create payload from %r" % obj)
TypeError: Cannot create payload from <coroutine object MediaUpload.aiter_file at 0x7ff91e08b840>
sys:1: RuntimeWarning: coroutine 'MediaUpload.aiter_file' was never awaited
```

**Comment by sanzoghenzo** [comment]
I forgot an `await`, but I'm not sure if it's the right thing to do... still some issues wrapping my head around async programming!

I understand that this is because I wrapped the `_aiter_file`, that was an async generator, inside the `MediaUpload.aiter_file`, that is a coroutine.

**Comment by omarryhan** [comment]
Python async is definitely challenging, at least compared to JS async programming.

I tested it and it works now. If you feel confident in your fix, I'll go ahead and merge. Unfortunately, I am stomped with work these days, so I can't review everything line by line.

**Comment by sanzoghenzo** [comment]
Sorry for the late reply, I'm trying another solution so that the payload would be an async iterator as it was before (my latest fix loads all the chunks before passing it to `MultiPartWriter`, not ideal) 

I've managed to remove it, but running an integration test using the file_body results in an upload of an empty file (at least using a simple byte text and saving it as a text file).

I need to do some more testing, so it will take a while...

**Comment by omarryhan** [comment]
Don't worry about it. Take your time :)

**Comment by sanzoghenzo** [comment]
Ok, I tried with a real binary payload (the content of a png image) and it works.

**Comment by omarryhan** [comment]
Heya, really sorry, work has been crazy the past couple of days and I haven't found time to test your PR. I'm working on testing it now

**Comment by omarryhan** [comment]
Perfect! PR works great. I'll release a new version now.

Thanks again! and sorry for the delay.

**Comment by omarryhan** [comment]
Released in version 2.1.0

**Pull request merged**
