### PR TITLE
Added example file

### PR DESCRIPTION
**Pull request by BebopChrome**
This is my full implementation of aiogoogle.

### CODE REVIEW

**Comment by omarryhan** [comment]
Thank you so much for taking the time to put this together.

Can you fix the lint issues reported by the CI please?

```bash
flake8 aiogoogle/examples/google_sheets_client.py
```

This will show you all the lint errors.

Also, I'm curious, what's the reason behind including both the sync and async?

**Comment by BebopChrome** [comment]
Yes I will look at the lint issue. This version of the client worked on python 3.9 but failed on python 3.7 so I have some updates to make. I needed both async and sync versions working to more easily migrate my existing program to async in stages. I left both versions in this example file to better demonstrate the differences between what people are probably already using and aiogoogle.

**Comment by BebopChrome** [comment]
Should be ready if you want to run CI check again

**Comment by omarryhan** [comment]
I fixed one more lint error.
In Python you'd generally want to use `is None` instead of `== None` in conditionals, because None is just a pointer to the same object. While both would work, the former is more terse.

**Comment by omarryhan** [comment]
I'll merge now. Thanks for your contribution!

**Comment by BebopChrome** [comment]
Glad to help. Yeah after 40 years of coding in 21 self taught languages I tend to do what works and try to clean it up later. Bad habits. I've been using both methods not knowing what was preferred in python. I'll switch to is None.

**Pull request merged**
