### PR TITLE
Do not mutate uri_params because it is used later.

### PR DESCRIPTION
**Pull request by amirouche**

### CODE REVIEW

**Comment by amirouche** [comment]
There is still a problem even with that PR.

What I trying to do looks like:

```python
            output = await aiogoogle.as_api_key(
                drive.files.export(fileId=file["id"], mimeType="text/html")
            )
```

**Comment by omarryhan** [comment]
Was there a bug that this PR fixed? Or was it just for good standards?

**Comment by amirouche** [comment]
Yes, there is a bug with `drive.files.export`

**Comment by omarryhan** [comment]
Can you post the error message here please?

**Comment by omarryhan** [comment]
Fixed in version 1.1.13. Thanks for attempting to fix it.

**Comment by amirouche** [comment]
Sorry for the absence of detailed bug report. And thanks for the fix!

**Pull request closed without merging**
